steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/$REPO_NAME:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build",
    "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID",
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    "."]
- name: gcr.io/cloud-builders/docker
  args: ['tag',
    'gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID',
    'gcr.io/$PROJECT_ID/$REPO_NAME:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:latest"]